version: '3.1'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $RDS_USERNAME
      MYSQL_DATABASE: $RDS_DB_NAME
      MYSQL_USER: $RDS_USERNAME
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nodejs-server:
    container_name: nodejs-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true 
    networks:
      - app-network

volumes:
  mysql-data:
networks:
  app-network:
    driver: bridge
